"""Python SDK for the Pragmatiks platform.

Core exports for provider authoring:
    Provider: Decorator for defining providers.
    Resource: Base class for provider resources.
    Config: Base class for resource configuration.
    Outputs: Base class for resource outputs.
    Field, FieldReference, Dependency: For cross-resource references.

Core exports for API consumers:
    PragmaClient: Synchronous HTTP client.
    AsyncPragmaClient: Asynchronous HTTP client.

Additional imports available from submodules:
    pragma_sdk.models: Data models (BuildInfo, ProviderStatus, etc.)
    pragma_sdk.types: Type definitions (LifecycleState, HealthStatus, LogEntry)
    pragma_sdk.context: Runtime context utilities
    pragma_sdk.platform: Platform resource types (SecretConfig, etc.)
"""

from pragma_sdk.client import (
    AsyncPragmaClient,
    AsyncProjectResources,
    PragmaClient,
    ProjectResources,
)
from pragma_sdk.exceptions import (
    ProjectHasResourcesError,
    ProjectMismatchError,
    ResourceFailedError,
)
from pragma_sdk.models import (
    AgentInstance,
    AgentInstanceStatus,
    AgentLogType,
    AgentType,
    AgentTypeCreate,
    AgentTypeUpdate,
    AssigneeCandidate,
    BoardSummary,
    BuildInfo,
    BuildStatus,
    CatalogEntry,
    CommentAuthorType,
    Config,
    ConversationRoutingManifest,
    CostEstimate,
    CreateProjectRequest,
    DeepAnalysisRequest,
    DeepAnalysisResponse,
    DeleteProjectRequest,
    Dependency,
    DeploymentResult,
    DeploymentStatus,
    ExplainTaskRequest,
    ExplainTaskResponse,
    Field,
    FieldReference,
    FileField,
    FileRef,
    FleetVitals,
    GenerateSubtasksRequest,
    GenerateSubtasksResponse,
    GraphDiff,
    Immutable,
    ImmutableDependency,
    ImmutableField,
    ImmutableSensitiveField,
    ImproveTaskRequest,
    ImproveTaskResponse,
    InvalidResourceIdentityError,
    LLMProviderSummary,
    ModelTier,
    MutationActorType,
    MutationOperation,
    Organization,
    OrganizationSettings,
    OrganizationStatus,
    Outputs,
    PaginatedResponse,
    PerformanceProfile,
    Project,
    ProposedSubtask,
    ProviderAuthor,
    ProviderComparisonRow,
    ProviderDeleteResult,
    ProviderInfo,
    ProviderInstallation,
    ProviderScope,
    ProviderVersion,
    ProviderVersionMetadata,
    PushResult,
    RegisterProviderVersionRequest,
    Resource,
    ResourceFieldDiff,
    ResourceIdentity,
    ResourceMutation,
    ResourceNetDelta,
    ResourceSchema,
    ResourceTier,
    ReviewSummaryRequest,
    ReviewSummaryResponse,
    ScheduleConfig,
    Sensitive,
    SensitiveDependency,
    SensitiveField,
    SensitiveOutput,
    SuggestAssigneeRequest,
    SuggestAssigneeResponse,
    SummarizeThreadRequest,
    SummarizeThreadResponse,
    Task,
    TaskActivityEntry,
    TaskActivityKind,
    TaskAssign,
    TaskComment,
    TaskCommentCreate,
    TaskCommentUpdate,
    TaskCreate,
    TaskMutationPage,
    TaskSource,
    TaskStatus,
    TaskTransition,
    TaskUpdate,
    UpdateProjectRequest,
    UpgradePolicy,
    VersionStatus,
)
from pragma_sdk.models import Provider as ProviderModel
from pragma_sdk.provider import Provider
from pragma_sdk.types import (
    CompatibilityConstraint,
    CopyContext,
    CopyResult,
    CopyStrategy,
    HealthStatus,
    LifecycleState,
    LogEntry,
    PatchDefinition,
    PatchResult,
)


__all__ = [
    "AgentInstance",
    "AgentInstanceStatus",
    "AgentLogType",
    "AgentType",
    "AgentTypeCreate",
    "AgentTypeUpdate",
    "AssigneeCandidate",
    "AsyncPragmaClient",
    "AsyncProjectResources",
    "BoardSummary",
    "BuildInfo",
    "BuildStatus",
    "CatalogEntry",
    "CommentAuthorType",
    "CompatibilityConstraint",
    "Config",
    "ConversationRoutingManifest",
    "CopyContext",
    "CopyResult",
    "CopyStrategy",
    "CostEstimate",
    "CreateProjectRequest",
    "DeepAnalysisRequest",
    "DeepAnalysisResponse",
    "DeleteProjectRequest",
    "Dependency",
    "DeploymentResult",
    "DeploymentStatus",
    "ExplainTaskRequest",
    "ExplainTaskResponse",
    "Field",
    "FieldReference",
    "FileField",
    "FileRef",
    "FleetVitals",
    "GenerateSubtasksRequest",
    "GenerateSubtasksResponse",
    "GraphDiff",
    "HealthStatus",
    "Immutable",
    "ImmutableDependency",
    "ImmutableField",
    "ImmutableSensitiveField",
    "ImproveTaskRequest",
    "ImproveTaskResponse",
    "InvalidResourceIdentityError",
    "LLMProviderSummary",
    "LifecycleState",
    "LogEntry",
    "ModelTier",
    "MutationActorType",
    "MutationOperation",
    "Organization",
    "OrganizationSettings",
    "OrganizationStatus",
    "Outputs",
    "PaginatedResponse",
    "PatchDefinition",
    "PatchResult",
    "PerformanceProfile",
    "PragmaClient",
    "Project",
    "ProjectHasResourcesError",
    "ProjectMismatchError",
    "ProjectResources",
    "ProposedSubtask",
    "Provider",
    "ProviderAuthor",
    "ProviderComparisonRow",
    "ProviderDeleteResult",
    "ProviderInfo",
    "ProviderInstallation",
    "ProviderModel",
    "ProviderScope",
    "ProviderVersion",
    "ProviderVersionMetadata",
    "PushResult",
    "RegisterProviderVersionRequest",
    "Resource",
    "ResourceFailedError",
    "ResourceFieldDiff",
    "ResourceIdentity",
    "ResourceMutation",
    "ResourceNetDelta",
    "ResourceSchema",
    "ResourceTier",
    "ReviewSummaryRequest",
    "ReviewSummaryResponse",
    "ScheduleConfig",
    "Sensitive",
    "SensitiveDependency",
    "SensitiveField",
    "SensitiveOutput",
    "SuggestAssigneeRequest",
    "SuggestAssigneeResponse",
    "SummarizeThreadRequest",
    "SummarizeThreadResponse",
    "Task",
    "TaskActivityEntry",
    "TaskActivityKind",
    "TaskAssign",
    "TaskComment",
    "TaskCommentCreate",
    "TaskCommentUpdate",
    "TaskCreate",
    "TaskMutationPage",
    "TaskSource",
    "TaskStatus",
    "TaskTransition",
    "TaskUpdate",
    "UpdateProjectRequest",
    "UpgradePolicy",
    "VersionStatus",
]
