"""Protocol between the Pragmatiks host and a provider worker.

Messages are JSON-RPC 2.0 frames over a Unix socket. The worker's first frame
is a ``handshake`` request; the host sends nothing before it accepts one.
"""

from pragma_sdk.protocol.codec import (
    ConnectionClosedError,
    FrameError,
    FrameTooLargeError,
    JsonRpcCodec,
    MalformedFrameError,
)
from pragma_sdk.protocol.constants import (
    APPLY_RESOURCE_METHOD,
    DISPATCH_METHOD,
    HANDSHAKE_METHOD,
    INTERNAL_ERROR_CODE,
    INVALID_PARAMS_CODE,
    JSONRPC_VERSION,
    MAXIMUM_FRAME_BYTES,
    METHOD_NOT_FOUND_CODE,
    MIGRATE_METHOD,
    OFFERED_PROTOCOL_VERSIONS,
    PROTOCOL_VERSION,
    RESOURCE_HEALTH_METHOD,
    RESOURCE_LOGS_METHOD,
    SHUTDOWN_METHOD,
    UNSUPPORTED_PROTOCOL_CODE,
    WAIT_FOR_STATE_METHOD,
)
from pragma_sdk.protocol.frames import (
    ApplyResourceParams,
    ChildResourcePayload,
    DispatchParams,
    Envelope,
    EnvelopeError,
    ErrorObject,
    FailureFrame,
    FrameKind,
    HandshakeParams,
    HandshakeResult,
    MigrateParams,
    MigrateResult,
    NotificationFrame,
    OwnerReferencePayload,
    ProtocolOffer,
    RequestFrame,
    ResourcePayload,
    ResourceQueryParams,
    ResourceTypeCapabilities,
    SuccessFrame,
    UnsupportedProtocolData,
    WaitForStateParams,
    WaitForStateResult,
)
from pragma_sdk.protocol.introspection import (
    IntrospectionFailure,
    IntrospectionReport,
    IntrospectionSuccess,
    ResourceTypeSchema,
)
from pragma_sdk.protocol.pending import PendingResponses
from pragma_sdk.types import EventType, HealthStatus, LifecycleState, LogEntry


__all__ = [
    "APPLY_RESOURCE_METHOD",
    "DISPATCH_METHOD",
    "HANDSHAKE_METHOD",
    "INTERNAL_ERROR_CODE",
    "INVALID_PARAMS_CODE",
    "JSONRPC_VERSION",
    "MAXIMUM_FRAME_BYTES",
    "METHOD_NOT_FOUND_CODE",
    "MIGRATE_METHOD",
    "OFFERED_PROTOCOL_VERSIONS",
    "PROTOCOL_VERSION",
    "RESOURCE_HEALTH_METHOD",
    "RESOURCE_LOGS_METHOD",
    "SHUTDOWN_METHOD",
    "UNSUPPORTED_PROTOCOL_CODE",
    "WAIT_FOR_STATE_METHOD",
    "ApplyResourceParams",
    "ChildResourcePayload",
    "ConnectionClosedError",
    "DispatchParams",
    "Envelope",
    "EnvelopeError",
    "ErrorObject",
    "EventType",
    "FailureFrame",
    "FrameError",
    "FrameKind",
    "FrameTooLargeError",
    "HandshakeParams",
    "HandshakeResult",
    "HealthStatus",
    "IntrospectionFailure",
    "IntrospectionReport",
    "IntrospectionSuccess",
    "JsonRpcCodec",
    "LifecycleState",
    "LogEntry",
    "MalformedFrameError",
    "MigrateParams",
    "MigrateResult",
    "NotificationFrame",
    "OwnerReferencePayload",
    "PendingResponses",
    "ProtocolOffer",
    "RequestFrame",
    "ResourcePayload",
    "ResourceQueryParams",
    "ResourceTypeCapabilities",
    "ResourceTypeSchema",
    "SuccessFrame",
    "UnsupportedProtocolData",
    "WaitForStateParams",
    "WaitForStateResult",
]
